ekf_filter_node:
  ros__parameters:
    frequency: 50.0  # Fréquence de mise à jour de l'EKF
    sensor_timeout: 0.2  # Timeout avant de considérer une donnée comme obsolète

    two_d_mode: false  # Mode 3D car le drone évolue dans les 3 dimensions

    print_diagnostics: true
    debug: true  # Active le mode debug
    debug_out_file: ~/dev_ws/debug/debug_ekf.txt

    publish_tf: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Configuration de l'IMU (ICM20948)
    imu0: /imu/data_raw  # Topic des données IMU brutes
    imu0_config: [false, false, false, false,  false,  false, false, false, false, true,  true,  true, true,  true,  true]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true  # Supprime la gravité des données d'accélération

    # Bruits des données de l'IMU (ajusté pour ICM20948)
    imu0_linear_acceleration_noise: 0.04  # Basé sur le bruit de l'accéléromètre ICM20948
    imu0_angular_velocity_noise: 0.0032  # Basé sur le bruit du gyroscope
    imu0_orientation_noise: 0.01  # Ajustez selon votre besoin

    # Biais estimés des données de l'IMU
    imu0_linear_acceleration_bias: 0.0001  # Ajuster selon l'étalonnage
    imu0_angular_velocity_bias: 0.0001  # Ajuster selon l'étalonnage

    # Données du magnétomètre (ICM20948)
    mag0: /imu/mag  # Topic des données magnétiques
    mag0_config: [false, false, false, false, false, false, true, true, true]  # Activer les 3 axes magnétiques
    mag0_differential: false
    mag0_queue_size: 10

    # Bruits des données magnétiques (ajusté pour le ICM20948)
    mag0_magnetic_field_noise: 0.05  # Ajusté selon la sensibilité de 0.15 µT/LSB
    mag0_orientation_noise: 0.02  # Ajustez si l'orientation dérivée est bruitée

    # Paramètres de covariance pour le filtre
    process_noise_covariance: 
      [1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
       0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
       0.0, 0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
       0.0, 0.0, 0.0, 1e-4, 0.0, 0.0, 0.0, 0.0, 0.0, 
       0.0, 0.0, 0.0, 0.0, 1e-4, 0.0, 0.0, 0.0, 0.0, 
       0.0, 0.0, 0.0, 0.0, 0.0, 1e-4, 0.0, 0.0, 0.0, 
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-6, 0.0, 0.0, 
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-6, 0.0, 
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-6]
